server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  application:
    name: spring-webflux-guide
  data:
    mongodb:
      database: FileStorageVideo
      host: localhost
      port: 27017

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
    reactor:
      netty:
        http:
          client: DEBUG



